### ISSUE TITLE
Samsung Galaxy S6 incorrect display parameters

### ISSUE THREAD

**Issue by zvxryb** [googlevr/webvr-polyfill#129]
The Galaxy S6 reports xdpi=522.5 and ydpi=576.6, resulting in incorrect distortion which is not radially symmetric.

**Comment by PixelPartner** [comment]
This bad value is also included in the JSON loaded from Google. So if you correct it in dpdb-cache.js, you should also call Dpdb(false, ...) to not load the bad JSON values. There's a bunch of other asymmetric dpi pairs and google even left out their new PIXELs.

And some newer SAMSUNG phones can be set to GAME MODE, reporting 1920x1080 instead of 2560x1440.
For those it might be useful to not only look for a matching UA, but also check the resolution and set another dpi (i.e. 435 instead of 576.7).

Could please someone at GOOGLE fix the https://storage.googleapis.com/cardboard-dpdb/dpdb.json accordingly.

**Comment by brianchirls** [comment]
I'm not getting a match at all for my S6, even an incorrect one. I think the Samsung ua rules are overly strict, as there may be multiple UA strings for all the different variants of the phone.

**Comment by jsantell** [comment]
Could you try https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/9 on this device and report back some info? We can currently match via resolution instead of user agent (like iOS devices) with a looser UA string and match both via `SM-G9` maybe? Agreed that the variations of UA are difficult to match specific phones.

**Comment by brianchirls** [comment]
@jsantell Is there a site or utility for checking that?

**Comment by brianchirls** [comment]
Oh, I see it now...

**Comment by brianchirls** [comment]
@jsantell Here's what I got:
Actual DPI X: 580.571
Actual DPI Y: 580.571
Screen Width: 2.48 inches
Screen Height: 4.41 inches
Width: 1440 pixels
Height: 2560 pixels

Not sure about bezel width, but I understand the device dimensions are:
143.4 x 70.5 x 6.8 mm (5.65 x 2.78 x 0.27 in)
These will be a little different for S6 Edge and S6 Edge+, but I don't know if the other stats above will be different as well.

**Comment by jsantell** [comment]
I think if my math is right, the bezel is 3.8 or ~4. What's the [user agent string](http://useragentstring.com/)? I'd think that the SM-G925F would match that device..

https://github.com/googlevr/webvr-polyfill/blob/b41b4a624a9b20f1605b8e40b9ad3315b0f079fa/src/dpdb/dpdb.json#L1230-L1243

**Comment by jsantell** [comment]
Moving Samsung resolution handling to fix incorrect distortions to https://github.com/googlevr/cardboard-vr-display/issues/7
