### ISSUE TITLE
Double vision on Pixel XL

### ISSUE THREAD

**Issue by garethwilliams** [googlevr/webvr-polyfill#176]
Using A-frame, on Nexus 5x WebVR scenes looks fine. However, when viewing WebVR scenes on a Pixel XL the stereoscopic does not match up, one of the eyes is too far apart. This causes double vision when viewing within a headset.

**Comment by borismus** [comment]
@btco Any chance we can update the dpdb with new Android devices?

On Thu, Nov 17, 2016 at 6:21 AM Gareth Williams <notifications@github.com>
wrote:

Using A-frame, on Nexus 5x WebVR scenes looks fine. However, when viewing
WebVR scenes on a Pixel XL the stereoscopic does not match up, one of the
eyes is too far apart. This causes double vision when viewing within a
headset.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlevr/webvr-polyfill/issues/176>, or mute the thread

**Comment by Ariel-zhangyue** [comment]
@borismus  
My android device is also not included in the dpdb_cache.js..and I do not know how to calculate it ..Could you please kindly tell me how to calculate "device"["rules"], ["bw"] and ["ac"] as well..?
Here is my device infomation, thanks in advance!!
<img width="344" alt="device_info1" src="https://cloud.githubusercontent.com/assets/22290786/20506391/a9d56a44-b08e-11e6-981a-21896fcff8ab.png">
<img width="341" alt="device_info2" src="https://cloud.githubusercontent.com/assets/22290786/20506392/ab03f408-b08e-11e6-81f2-6fc250bf2453.png">



and some js console message when test webpage based on  A-frame on Android device:
<img width="951" alt="console_screenshot" src="https://cloud.githubusercontent.com/assets/22290786/20506406/ccbde540-b08e-11e6-94d5-9e0473994d67.png">

**Comment by AdrienPoupa** [comment]
Hello,

Any progress on this. It's really disturbing not to be able to use a recent device in a cardboard.

**Comment by Ariel-zhangyue** [comment]
@AdrienPoupa  yes, I add some additional information in DBPB cache file,
you can refer to this link[https://github.com/aframevr/aframe/issues/2117#issuecomment-265275683](url)

I get my device information from [https://play.google.com/store/apps/details?id=com.jphilli85.deviceinfo](url)

It seems they just match 'ua' and 'res' rules , so make sure "ua"(user agent I guess) is correct.
We have to wait till Google updates that database... 
Have a try to fix it locally...

**Comment by jsantell** [comment]
In #233, the local DPDB has been updated and sync'd with the online version at webvr.rocks (once https://github.com/WebVRRocks/webvr-polyfill-dpdb/pull/7 is merged), which includes the Pixel XL. Try the latest version which should fix this -- please reopen if this does not fix the issue. Thanks!
