### ISSUE TITLE
Offer to Maintain the Online DPDB Cache

### ISSUE THREAD

**Issue by thoragio** [googlevr/webvr-polyfill#184]
I've created a copy of the online DPDB cache here:
https://rawgit.com/thoragio/webvr-polyfill-dpdb/master/dpdb.json

And my repo for it is here:
https://github.com/thoragio/webvr-polyfill-dpdb

There have been a few requests to add new devices to this list over the last couple of months, so I am proposing to maintain this list at the links above. I would also continue to post PRs to your repo so that the offline cache in your repo is eventually kept up-to-date with the online one at the URL above.

If you guys are happy with this, I suggest to change the `ONLINE_DPDB_URL` to the rawgit.com URL above in `src/dpdb/dpdb.js`. Let me know and I will submit the required PR.

**Comment by thoragio** [comment]
@borismus - friendly ping to get your feedback on my offer to maintain the online DPDB cache. Thanks.

**Comment by kfarr** [comment]
+1 this is a big blocker for a-frame users; lack of proper iOS support is not good

**Comment by kfarr** [comment]
In fact, just looking through the issues, a good chunk of issues are directly related to maintaining the DPDB:
- https://github.com/googlevr/webvr-polyfill/issues/129
- https://github.com/googlevr/webvr-polyfill/issues/139
- https://github.com/googlevr/webvr-polyfill/issues/164
- https://github.com/googlevr/webvr-polyfill/issues/176
- https://github.com/googlevr/webvr-polyfill/issues/181
- https://github.com/googlevr/webvr-polyfill/issues/188

While @thoragio's offer may not help solve all of them, it could make a big dent immediately.

**Comment by borismus** [comment]
Sorry for the delay here. DPDB is generated from an internal database which has since gone stale. We need to work out a better story, please stay tuned.

**Comment by brianchirls** [comment]
I'd like to give this a bump and re-iterate the importance of getting this fixed.

Even though Chrome is making progress toward native Cardboard support, it's still some way off before it's supported in WebViews or [Chrome Custom Tabs](https://bugs.chromium.org/p/chromium/issues/detail?id=688611), which includes progressive web apps installed to home screen, not to mention Firefox, Samsung Internet, Mobile Safari, etc. And I'm seeing more and more cases of unmatched phones, which results in distortion so bad it's nearly unusable, especially as screens get bigger.

Since I can't find any documentation online of the source for this database or it being used in any other projects, I'm not opposed to forking it and either maintaining it here or in another repo.

In any case, if the online database is so unreliable, we should not be obliterating the cache when the remote database is loaded. Perhaps just append the new entries to the existing array, or insert them at the top. Maybe make it configurable.

**Comment by jbreckmckye** [comment]
Currently A-Frame maintains a fork with its own DPDB cache data. It might be worth using that instead until upstream gets fixed.

**Comment by HalfdanJ** [comment]
@toji any good ideas how this can get a better workflow? Seems like one of the main reasons for a-frames fork.

**Comment by cvan** [comment]
@HalfdanJ I'd recommend the following:

1. accept PRs to make [`DPDB_CACHE`](https://github.com/googlevr/webvr-polyfill/blob/cca430bbff0a29c0bd2b6b8a78ef6da82fb539cf/src/dpdb/dpdb-cache.js) ensure it's as up to date as possible; it's [used here](https://github.com/googlevr/webvr-polyfill/blob/c484e22ca9c10b279d91c736a6a33a86d3cd1e3e/src/dpdb/dpdb.js#L18), as a fallback
2. allow `ONLINE_DPDB_URL` to be a configurable setting, if people need newer/different projections and configurations: https://github.com/googlevr/webvr-polyfill/blob/c484e22ca9c10b279d91c736a6a33a86d3cd1e3e/src/dpdb/dpdb.js#L22
3. allow a custom setting (e.g., a `DPDB_OVERRIDES` method) that can manipulate (append, remove, insert, cancel, etc.) the DPDB calls.

**Comment by cvan** [comment]
Friendly ping, @toji, @HalfdanJ: what do you think of @thoragio's suggestion about maintaining the DPDB? Or any advice on other ways the DPDB can be maintained going forward?

**Comment by HalfdanJ** [comment]
I think this sounds like a good solution.

**Comment by toji** [comment]
Sounds good to me!

**Comment by thoragio** [comment]
OK. I have submitted the [PR](https://github.com/googlevr/webvr-polyfill/pull/220).
