### ISSUE TITLE
Nosleep stopped working on iOS 10.3.1

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-polyfill#217]
New version of iOS has broken the no sleep functionality in polyfill.

**Comment by jsantell** [comment]
Looks like others reporting the same with [NoSleep.js](https://github.com/richtr/NoSleep.js/issues/29), urg.

**Comment by customlogic** [comment]
This has been fixed in NoSleep: https://github.com/richtr/NoSleep.js/issues/29

**Comment by jsantell** [comment]
Just tried the latest nosleep and didn't seem to work for iOS11 :\

**Comment by jeppester** [comment]
I experience the same problem on iOS 11.1.2.

I took the time to run some tests with nosleep and webvr-polyfills wakelock.

webvr-polyfill's built-in wakelock (using location hack) doesn't have any effect - the screen goes to sleep after 40 seconds, every time.

With the latest nosleep.js (using a looped video) the results get really interesting. I get between ~40 and ~80 seconds before the screen goes to sleep. Because of the variance in the number of seconds I tested a LOT of times. It almost seems like some randomness was added intentionally. Here are my numbers:
60, 79, 70, 40, 42, 46, 82, 50

I'll try out various solutions, to see if I can come up with something the works, here are my current ideas:
- instead of using a data URI try loading the video from a file
- try a longer video
- try making the video visible on the screen

**Comment by jeppester** [comment]
Update: Using a longer video works.
Maybe there is a way to programatically loop parts of the base64 string to increase the length of the video.

**Comment by cvan** [comment]
great idea! looks like we can do https://github.com/richtr/NoSleep.js/blob/master/src/index.js#L20-L24 (fixed in richtr/NoSleep.js#33)

I can take this on, unless someone beats me to it

**Comment by jeppester** [comment]
The fix you are referring to is included in the latest NoSleep.js-version, which is the one I was testing. It does work to some extend, but it seems like it doesn't fool safari for very long.

My idea was to programmatically repeat parts of the base64 string to make the video's duration longer. I'm not entirely sure if it's a good idea though, it will take up some extra memory to store a very long data URI.

**Comment by jsantell** [comment]
Looks like there's an issue open for iOS11 not working, but possibly fixed in 11.1? Can anyone else confirm? https://github.com/richtr/NoSleep.js/issues/41

**Comment by jsantell** [comment]
Fix for iOS 10 ready (https://github.com/googlevr/cardboard-vr-display/pull/1), will open a new ticket for iOS 11 issues

**Comment by jsantell** [comment]
Fixed in https://github.com/googlevr/webvr-polyfill/commit/71eb2151e75e0ce056dd7b69f43b6a0299df9507, 0.10.1
