### ISSUE TITLE
Asynchronous lazy loading

### ISSUE THREAD

**Issue by brianchirls** [googlevr/webvr-polyfill#255]
For most of my WebVR projects, the polyfill is the single biggest script component apart from three.js, and it would be great to avoid loading it altogether or at least defer loading it as long as possible.

If we can guarantee a synchronous test to determine whether we need the polyfill at all, then we can check it early and just skip loading. Certainly if the WebVR API doesn't exist at all (and we're on a mobile device with orientation support), then we know we need the polyfill. But then the question is whether we're guaranteed to have at least one working WebVR display (i.e. Cardboard).

According to [webvr.rocks](https://webvr.rocks/), it looks like all polyfillable browsers support Cardboard except Servo. I know that was not the case with Chrome a couple months ago, but that seems to have been fixed. I'm not sure how all the edge cases are handled like missing/expired Origin Trial tokens, etc. And a quick test shows no support for Cardboard in Samsung Internet. Can anyone here comment definitively?

As it is, this polyfill will create a fake Cardboard device if the browser supports the API but does not provide any displays. If that's still necessary, it would be great to be able to lazy load the polyfill and have it fire `vrdisplayconnect` (or eventually `deviceconnect` for 2.0) once it's loaded. It will, however, be necessary to have a separate initial script that synchronously polyfills `getFrameData` early on - see 42e31a18b101d1230d29ff7e11e08772878d223f and #197

**Comment by brianchirls** [comment]
After talking to @klausw on WebVR Slack, it sounds like Chrome will always provide the Cardboard device but only if Google VR Services are installed and have proper permissions configured. It appears this requires Android K (4.4) or later and a compatible device. So I'd say the polyfill is still necessary, even when the WebVR API is available.

Reference: https://bugs.chromium.org/p/chromium/issues/detail?id=670166#c56

I'd be willing to take a stab at a pull request. Before I do, is there any additional feedback?

**Comment by klausw** [comment]
As a side note, personally I'd prefer discouraging using the polyfill on a device that would be capable of a lower-latency native experience.

Of course there may well be situations where people can't or don't want to install the VR services, but I would prefer if in those cases there's some user visible feedback about a fallback being used with a possibly degraded experience instead of just transparently dropping people into the polyfill.

**Comment by brianchirls** [comment]
@klausw Fair enough, but I think that should happen on a case by case basis depending on the content.

**Comment by cvan** [comment]
This is a very good and legitimate issue to bring up.

I know it's just deferring the problem – and I'm not necessarily suggest doing this – but do you think lazy-loading could instead by handling conditionally in the developer's JS ([here's an example](https://github.com/jakearchibald/svgomg/blob/9d09a4d/src/js/page/index.js) of a common pattern I've seen)?

IMO, it'd be ideally if there were two bundles: (1) a small loader script that checks for the existence of the native WebVR API and, if not found, asynchronously injects a `<script>`; (2) the main script to polyfill the WebVR API.

Currently, most of the WebVR sites I've seen in the wild synchronously block the site's rendering on a `<script src="webvr-polyfill.min.js"></script>` tag (or within a bundle generated by a Browserify/Webpack/Rollup/etc. build system).

How would you expect sites to sniff for WebVR API support after the Polyfill (loader) has loaded? Two options come to mind:

1. Tell developers to listen for some event that fires on `window` (e.g., `vrpolyfillinject`) so they know when to proceed with anything that's dependent on the presence of the WebVR API.
2. Expect developers to introduce a `<script src="webvr-polyfill.loader.min.js"></script>` tag, which would block their site's JS code that depends on the WebVR API. (But, this script would be tiny, and ideally would be cached on a CDN/server - and even better if also cached using a Service Worker.)

The problem with option #1 is that when the native WebVR API _does_ is supported and present in the User Agent, there is no browser-level event fired.

When discussing permissions and detecting API support, in the WebVR spec, we've brought up the possibility of using the [Permissions API (`navigator.permissions`)](https://w3c.github.io/permissions/) as a method of allowing developers to express intent to use the API (enabling the user to grant or deny requests to enter VR, which could obviously prove useful; admittedly, the user-gesture requirement for auto-entering VR is already a headache, and this could complicate things).

There's also a new spec, the [Feature Policy API](https://github.com/WICG/feature-policy), which is designed for exactly this type of check.

Lazy-loading the Polyfill is a solid idea. Though this project is supposed to be just a Polyfill, so perhaps a separate project/module could be created that packages the `webvr-polyfill` with a loader and injects the main WebVR Polyfill script on an as-needed basis.

Thoughts?

**Comment by brianchirls** [comment]
@cvan We're close on this one. Yes, I agree with breaking the script up into two pieces and loading the second part asynchronously, but the first part really needs to polyfill `VRFrameData` early and synchronously because `THREE.VRControls` and other scripts like it will instantiate that before we know whether we need it (again, see 42e31a1 and #197). That first script should also probably provide a test function that checks whether it's a mobile device.

I *really* don't want to block anything else synchronously, and I don't think we need to. That can go very wrong and really slow things down, even if it's a small script.

It should be up to the individual developer how to decide whether to load the second part of the polyfill. I can imagine a few scenarios:
- Load the polyfill immediately if and only if there is no native WebVR implementation, per @klausw's suggestion above.
- Load the polyfill if and only if it's a mobile device. Even if the WebVR API is supported, we may not get a Cardboard display back if the OS doesn't provide it, and we can't know that synchronously.
- If no WebVR API, load the polyfill. Otherwise, run `getVRDisplays` and wait for a response. Then, if the device list comes back empty *and* it's a mobile device, load the polyfill.

Personally, I'd probably go with the last one. There's a very short delay in starting to load the polyfill when we need it, but we really avoid loading it unless it's going to be helpful.

I don't think we need a `vrpolyfillinject` event, because it would be sufficient to just fire `vrdisplayconnect` as in #258.

**Comment by jsantell** [comment]
Going back through the comments here in light of future plans and [0.10.0](https://github.com/googlevr/webvr-polyfill/releases/tag/v0.10.0) release, which simplifies the injection, this is a tricky problem. Some thoughts..

If you want the VR experience to always work on mobile, it's necessary to always include the polyfill when the API exists but no VRDisplays are available. The polyfill is 178kb, which 170kb of it is the cardboard vr display.

Things like `THREE.VRControls` that use `VRFrameData` on instantiation seems in userland or VRControls responsibility -- I don't think it's reasonable for the polyfill to handle this case, and can be solved with delaying instantiating the controls. Three is also moving to use `renderer.vr`, which also uses the frame data upon instantiation.

There are a few solutions here, but all dependent on what kind of support you'd like to provide for your experience, and ultimately don't think it's the polyfill's responsibility. Having two separate scripts would add complexity to the 'drop a script on a page' brute force simplicity that other polyfills provide. I think this can be solvable in user land in a straight forward way:

```js
if (navigator.getVRDisplays) {
  navigator.getVRDisplays.then(displays => {
    if (!displays.length) {
      inject('js/webvr-polyfill');
      new WebVRPolyfill();
      // call polyfilled getVRDisplays
      navigator.getVRDisplays.then(displays => start(displays[0]));
    }
    else {
      start(displays[0]);
    }
  });
}
```

Also, since VRDisplays are only used when on desktop with native support (Vive, Oculus) or mobile native support (GearVR, Daydream), and with the polyfill surface area being rather small (VRFrameData/navigator.getVRDisplays), you could also optionally just load directly the [CardboardVRDisplay](https://github.com/googlevr/cardboard-vr-display) and create a VRFrameData constructor (like in the [cardboard-vr-display example](https://github.com/googlevr/cardboard-vr-display/blob/9903064f3b6120a769bbe2f3b1bf10a0924fd131/examples/index.html#L105-L121)) for a lighter weight solution that doesn't clobber any globals. This lightweight solution I think will get more tricky in a 2.0 world, though.

--

I'm closing this for now, I don't think this is in the polyfill's responsibility, and while nice to have, it's difficult to generalize for all use cases and adds complexity to including the script, and can be handled in user land with a few lines of code. If i'm misunderstanding the issue or missing something, please reopen and lets discuss more!
