### ISSUE TITLE
webvr-polyfill 0.9.34 breaks on Chromium Desktop with Rift

### ISSUE THREAD

**Issue by ngokevin** [googlevr/webvr-polyfill#263]
1. Use Chromium June build on Windows.
2. Reproduced on A-Frame master using 0.9.34.
3. Try to enter VR, only enters full screen, and Rift displays "Please wait..."

Reverting aframevr/aframe#ebf12fff74a3323598fb4c34b9144ed86725ae77 to the previous branch of the polyfill removes this issue. So we have isolated the issue to the polyfill.

**Comment by dmarcos** [comment]
It also reproduces on the webvr.info samples: https://webvr.info/samples/XX-vr-controllers.html

**Comment by ngokevin** [comment]
Currently bisecting. It works still on 1ad34f928344008cb17e3f72c188440d9881883f (0.9.28)

**Comment by ngokevin** [comment]
Does not work on f43a2098c47ee02a8d5e64fd9c8fc71b0bc51e6f (0.9.30), continuing to bisect.

**Comment by ngokevin** [comment]
The offending patch seems to be c3d89f35048a3d1bc8fbc93947c75b15dbfcfaad

`Polyfill VRFrameData enabled on all devices`

**Comment by ngokevin** [comment]
I wonder why the whole block of code about polyfilling VRFrameData if `window.VRFrameData` exists. It seems it used to only apply to mobile devices with native WebVR.

**Comment by brianchirls** [comment]
@ngokevin I have explained why that exists in #197.

It's not clear to me why c3d89f3 would have caused this problem, and I may not be able to schedule access to a rift to test it today. Sorry to ask a stupid question, but just to be absolutely thorough, are you sure you did a full rebuild and cache-busting reload on every step of the bisect?

**Comment by ngokevin** [comment]
Yeah, I rebuilt the file, reinstalled via npm locally, restarted my Browserify server, and refreshed the browser on each step. I then double-checked by unapplying the patch, seeing it was broken, then applying the patch, and seeing it was fixed for the case.

**Comment by brianchirls** [comment]
Nice.

Is there any error or warning in the console?

**Comment by ngokevin** [comment]
Nope, the only symptoms are described in the original issue description with presenting VR.

**Comment by brianchirls** [comment]
Okay, I think I figured it out. It looks like A-Frame is creating an instance of THREE.VRControls *before* enabling the polyfill. VRControls creates a *native* instance of `VRFrameData` before `WebVRPolyfill.prototype.enablePolyfill` has a chance to replace `window.VRFrameData`. So later on, when the polyfilled `getFrameData` tries to write to `frameData.pose`, it's setting that read-only property on the native object instead of the polyfilled one. Chromium doesn't like that.

So the solution is as follows:
1. Have polyfilled `window.VRDisplay.prototype.getFrameData` check if the `VRFrameData` object passed to it is a real native one or a polyfilled one. If it's native, then just run `nativeGetFrameData` on that native object and exit. Otherwise, proceed with the copying as it does now.
2. Make sure A-Frame loads and enables the polyfill before setting up either `THREE.VRControls` or `THREE.VREffect`. Not strictly necessary to fix Vive/Rift, but it should help for Android devices without Google VR Services installed (i.e. native webvr with no displays).

I will take a crack at a pull request tomorrow morning if I have time. You don't have to revert 1ac010e, so if someone can test my PR on all the proper hardware and it works, we can close #264.

**Comment by jsantell** [comment]
@brianchirls that sounds like it'd do the trick, thank you for digging into this!

**Comment by brianchirls** [comment]
Okay @jsantell and @ngokevin, there it is. Please (build and) test.
