### ISSUE TITLE
Does WakeLock necessary to be created when polyfill runs on desktop?

### ISSUE THREAD

**Issue by shaoboyan** [googlevr/webvr-polyfill#275]
According to [WakeLock.js](https://github.com/googlevr/webvr-polyfill/blob/master/src/wakelock.js#L69)
and [base.js](https://github.com/googlevr/webvr-polyfill/blob/master/src/base.js#L72)
WakeLock will be created in default.  I totally understand it is important on android or ios device. 
But does it needed on windows? 
p.s. I find this when  I did some 360 video performance tesing on windows desktop , and I find the page loaded more videos than I expected.

**Comment by cvan** [comment]
good call – you're correct, we shouldn't be doing this. `base.js` ought to be changed to only conditionally serve or change [`wakelock.js`](https://github.com/googlevr/webvr-polyfill/blob/145b668/src/wakelock.js#L73-L74) to return and [execute](https://github.com/googlevr/webvr-polyfill/blob/4bdb770/src/base.js#L72) a no-op `WakeLock` instead of returning `AndroidWakeLock` by default for non-iOS devices.

thanks for filing this issue.

**Comment by jsantell** [comment]
Fixed in 0.10.2
