### ISSUE TITLE
Cannot start VR programmatically even though full screen is already started

### ISSUE THREAD

**Issue by jeppester** [googlevr/webvr-polyfill#292]
I'm trying to implement a flow similar to this demo:
https://petravr.withgoogle.com/

The flow is basically:
1. Let the user choose the type of experience. Prevent sleep and on launch fullscreen mode (on Android) from the button press.
2. Ask the user to rotate the screen
3. When the screen has been rotated to landscape mode, start the stereoscopic rendering

On iOS this works fine, because iOS Safari has no fullscreen API.

Unfortunately on Android webvr-polyfill does a failing `requestFullscreen`-call (because the request doesn't come from a user event), which seems to prevent the scene from starting stereoscopic rendering.

Here's the specific line:
https://github.com/googlevr/webvr-polyfill/blob/master/src/base.js#L282

My problem is somewhat related to this:
https://github.com/aframevr/aframe/issues/1933

I wish I could take control of whether or not webvr-polyfill tries to launch full screen mode.

**Comment by jsantell** [comment]
Thanks for filing! According to the 1.1 spec, [requestPresent](https://w3c.github.io/webvr/spec/1.1/#dom-vrdisplay-requestpresent) must be called within a user gesture. This is failing on Android for you due to fullscreen API having the same limitation -- this will also fail on a VR device (Vive, oculus, daydream, gear vr), so I don't think a workaround for the Android fullscreen is appropriate. Could you trigger the `requestPresent` from the user selection? The cardboard implementation inside the polyfill will trigger a rotation display and prompt the user to rotate as well similar to your step 2.

**Comment by jeppester** [comment]
If I use `requestPresent` directly from the user gesture, the `onFullscreenChange` callback will automatically rotate the screen (if possible) preventing me from showing an instructions screen.

I don't see how I can then create an experience similar to the petra vr demo without patching `VRDisplay.prototype.requestPresent` to not automatically rotating my screen.

**Comment by jeppester** [comment]
I've made the flow work by patching `requestPresent` to always request fullscreen on the document body, and to not rotate and lock the screen.

In case anyone needs a similar flow, here are the changes:

To use `document.body` as fullscreen element, and to not wrap it, replace [this line](https://github.com/googlevr/webvr-polyfill/tree/2c48091d905cf6b084d2f56e66b353fd3a0ae7aa/src/base.js#L238):
`var fullscreenElement = self.wrapForFullscreen(self.layer_.source);`

with:
`var fullscreenElement = document.body`

Since the object is no longer wrapped, all occurences of `self.removeFullscreenWrapper()` can be removed.

To prevent the screen from getting rotated, comment out the following [lines](https://github.com/googlevr/webvr-polyfill/tree/2c48091d905cf6b084d2f56e66b353fd3a0ae7aa/src/base.js#L245):
```es
if (screen.orientation && screen.orientation.lock) {
  screen.orientation.lock('landscape-primary').catch(function(error){
          console.error('screen.orientation.lock() failed due to', error.message)
  });
}
```

**Comment by cvan** [comment]
@jeppester do you have a demo URL or video of this flow? I _think_ I understand what you're trying to do.

<hr>

I figured this isn't entirely the same issues you're trying to solve, but I figured I'd bring it up here because it may help you…

A-Frame uses the WebVR Polyfill, primarily for handling Google Cardboard on iPhone.

the WebVR Polyfill's "faux-fullscreen" is actually helpful (though limited in capability). a user can click on an "Enter VR" button and rotating the phone's orientation to landscape "just works."

I like that flow personally, but there are a few issues because portrait locks prevents the events from knowing the phone changed orientation:

- https://github.com/aframevr/aframe/issues/1239
- https://github.com/aframevr/aframe/issues/2992
- https://github.com/aframevr/aframe/issues/2577

when the Fullscreen API is available (i.e., Chrome/Firefox for Android), obviously, that ought to be used.

**Comment by jsantell** [comment]
What is the ideal scenario here? My understanding is that these things should be handled outside of VR presentation -- if you call `requestPresent`, the fullscreen and orientation changes occur, and this would also occur on a native VR platform like Daydream or Vive, and any custom instructions would also have to deal with this scenario on how the WebVR API works. Infact, trying the [Petra VR demo](https://petravr.withgoogle.com/), it has its own "please orient your device" screen with a 5 second timer on it, and it only uses cardboard (so that on a Pixel device on Chrome with WebVR enabled, it does not use the Daydream VRDisplay).

I think this is maybe something the new spec could handle, some way to display some content between the user interaction and entering VR.

**Comment by jsantell** [comment]
Following up on https://github.com/googlevr/webvr-polyfill/issues/292#issuecomment-355063643, it's possible to style that experience similarly -- the Petra demo just begins rendering the stereoscopic view immediately and uses that to show a loader. If you disable the cardboard UI as well as rotation instructions, your WebVR experience can display whatever it wants stereoscopically immediately. I think this will give you the same experience as that demo, fully customizable. If I'm misunderstanding, please let me know!

Options:
```
  // Flag to disabled the UI in VR Mode.
  CARDBOARD_UI_DISABLED: true,

  // Flag to disable the instructions to rotate your device.
  ROTATE_INSTRUCTIONS_DISABLED: true,
```

**Comment by jeppester** [comment]
The spec doesn't allow [requestPresent](https://immersive-web.github.io/webvr/spec/1.1/#dom-vrdisplay-requestpresent①) to present HTML, it takes a [VRLayerInit](https://immersive-web.github.io/webvr/spec/1.1/#typedefdef-vrsource) object, and the source of a [VRLayerInit](https://immersive-web.github.io/webvr/spec/1.1/#typedefdef-vrsource) can only be a canvas.

The reason that [cardboard-vr-display](https://github.com/googlevr/cardboard-vr-display) can show a rotation instructions screen, is that it internally wraps the source canvas in a `div`, and that `div` is then used as container for the rotate instructions overlay.

So currently I don't see any other option than hacking around with the VRDisplay if I want a custom rotation instructions screen (or any other non-stereoscopic non-canvas overlay).

As I see it a solution that follows the spec would have to follow this flow:
1. Show HTML while not presenting (including information about screen rotation, how to mount vr goggles etc.)
2. Launch presentation from a user event (a button click)
3. Show a stereoscopic canvas while presenting

I guess the real problem here is that petravr's and cardboard-vr-display's rotation screen's behaviours are doing things that the spec doesn't account for in order to improve the user experience.

Maybe the spec could allow presentation to start from a non-user event if the source canvas is inside the document's current fullscreen element.

**Comment by jsantell** [comment]
@jeppester filed a follow up question to the WebXR spec: https://github.com/immersive-web/webxr/issues/315, I think it's unclear in some regards how this will work.

* Would the ability to load your own image for the interstitial solve this use case? https://github.com/googlevr/webvr-polyfill/issues/210
* Is this experience only supporting Cardboard, not native WebVR? I.e. what's the expected experience on a Daydream/GearVR device?
